import CategoriesSelection from "@/components/storFont/CategoriesSelection";
import FeaturedProducts from "@/components/storFont/FeaturedProducts";

import Hero from "@/components/storFont/Hero";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "ZeroShow - Home",
  description: "Generated by create next app",
};
export default async function IndexPage() {
  return (
    <div>
      <Hero />
      <CategoriesSelection />
      <FeaturedProducts />
    </div>
  );
}
